#!/usr/bin/env python3
"""Build and check the node-notes layer (node-notes/).

node-notes/ holds short "field practice" notes that AgentOS nodes fetch from
this public repository and hand to an agent only when it asks for them. A
merged main IS the publication: there is no release step and no write token.
Nodes read node-notes/node-notes.json at a commit sha, so the bundle is
generated by this script inside the pull request and committed; CI rebuilds it
and requires a byte-for-byte match.

Format of a note and the limits: node-notes/README.md.

COMMANDS (run from the repository root)

  python3 .github/node-notes.py build
      Regenerate node-notes/node-notes.json from node-notes/*.md.

  python3 .github/node-notes.py check [--latest-core X.Y.Z] [--routine-fields PATH|URL]
      Read-only. Layout, front matter schema, unique ids, 4 KB per note and
      64 KB per bundle, English only, no ```yaml blocks and no routine schema
      field keys in a note, AUTHORS syntax, and "the committed bundle is
      current". The latest core tag (for min_core) and the routine field list
      are only needed when at least one note exists: an empty catalog is
      green offline. With notes present, a missing tag or a missing
      routine-fields.json asset is RED, never a silent pass.

  python3 .github/node-notes.py authors --base SHA --head SHA --author LOGIN
      Pull-request gate. When the change touches node-notes/** (or this
      script, or its workflow), LOGIN must be listed in node-notes/AUTHORS as
      it exists in the BASE commit -- a pull request cannot add its own author.
      The workflow runs the base commit's copy of this script for the same
      reason.

Exit codes: 0 green, 1 a finding, 2 usage or environment error.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

NOTES_DIR = "node-notes"
BUNDLE_NAME = "node-notes.json"
AUTHORS_NAME = "AUTHORS"
README_NAME = "README.md"
BUNDLE_FORMAT = 1

NOTE_MAX_BYTES = 4 * 1024
BUNDLE_MAX_BYTES = 64 * 1024
TITLE_MAX_CHARS = 120

# Paths whose change requires an author from AUTHORS, besides node-notes/**:
# the checker and its workflow decide what "green" means for the notes.
GATED_FILES = (".github/node-notes.py", ".github/workflows/node-notes.yml")

# The routine schema field list ships as an asset of every core release v*.
DEFAULT_ROUTINE_FIELDS_URL = (
    "https://github.com/try-agent-os/agentos/releases/latest/download/routine-fields.json"
)

REQUIRED_KEYS = ("id", "title", "min_core", "source")
OPTIONAL_KEYS = ("max_core", "requires_tools")
KNOWN_KEYS = REQUIRED_KEYS + OPTIONAL_KEYS

ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$")
SEMVER_RE = re.compile(r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$")
TAG_RE = re.compile(r"^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$")
TOOL_RE = re.compile(r"^[A-Za-z0-9_.:-]{1,64}$")
LOGIN_RE = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})$")
CYRILLIC_RE = re.compile("[\u0400-\u052f]")
YAML_FENCE_RE = re.compile(r"^\s*(```|~~~)\s*\{?\s*\.?ya?ml\b", re.IGNORECASE)
KEY_LINE_RE = re.compile(r"^\s*(?:-\s+)?[\"']?([A-Za-z_][A-Za-z0-9_]*)[\"']?\s*:(?:\s|$)")
INLINE_CODE_RE = re.compile(r"`([^`\n]+)`")
INLINE_KEY_RE = re.compile(r"(?:^|[\s{,\-])[\"']?([A-Za-z_][A-Za-z0-9_]*)[\"']?\s*:(?:\s|$)")


class Finding(Exception):
    """A rule the tree breaks."""


# --------------------------------------------------------------------------
# parsing


def parse_semver(value: str) -> tuple[int, int, int] | None:
    m = SEMVER_RE.match(value)
    return (int(m[1]), int(m[2]), int(m[3])) if m else None


def parse_scalar(raw: str) -> str:
    raw = raw.strip()
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in "\"'":
        return raw[1:-1]
    return raw


def parse_list(raw: str, where: str) -> list[str]:
    raw = raw.strip()
    if not (raw.startswith("[") and raw.endswith("]")):
        raise Finding(f"{where}: requires_tools must be a list like [a, b]")
    inner = raw[1:-1].strip()
    if not inner:
        return []
    return [parse_scalar(part) for part in inner.split(",")]


def parse_note(path: Path) -> dict:
    """Return the note as a bundle entry. Raises Finding on any rule break."""
    where = f"{NOTES_DIR}/{path.name}"
    data = path.read_bytes()
    if len(data) > NOTE_MAX_BYTES:
        raise Finding(f"{where}: {len(data)} bytes, the limit is {NOTE_MAX_BYTES} per note")
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        raise Finding(f"{where}: not valid UTF-8") from None
    text = text.replace("\r\n", "\n")
    lines = text.split("\n")
    if not lines or lines[0] != "---":
        raise Finding(f"{where}: must start with a '---' front matter line")
    try:
        end = lines.index("---", 1)
    except ValueError:
        raise Finding(f"{where}: front matter is not closed by a '---' line") from None

    fields: dict[str, str] = {}
    for n, line in enumerate(lines[1:end], start=2):
        if not line.strip():
            continue
        m = re.match(r"^([a-z_]+):(.*)$", line)
        if not m:
            raise Finding(f"{where}:{n}: front matter line is not 'key: value'")
        key, raw = m[1], m[2]
        if key not in KNOWN_KEYS:
            raise Finding(f"{where}:{n}: unknown front matter key '{key}'")
        if key in fields:
            raise Finding(f"{where}:{n}: duplicate front matter key '{key}'")
        fields[key] = raw
    for key in REQUIRED_KEYS:
        if key not in fields or not parse_scalar(fields[key]):
            raise Finding(f"{where}: required front matter key '{key}' is missing or empty")

    note: dict = {}
    note_id = parse_scalar(fields["id"])
    if not ID_RE.match(note_id):
        raise Finding(f"{where}: id '{note_id}' must be 3-64 chars of [a-z0-9-]")
    if path.stem != note_id:
        raise Finding(f"{where}: file name must be '{note_id}.md' (the id)")
    note["id"] = note_id

    title = parse_scalar(fields["title"])
    if len(title) > TITLE_MAX_CHARS:
        raise Finding(f"{where}: title is longer than {TITLE_MAX_CHARS} characters")
    note["title"] = title

    min_core = parse_scalar(fields["min_core"])
    if parse_semver(min_core) is None:
        raise Finding(f"{where}: min_core '{min_core}' is not a semver X.Y.Z")
    note["min_core"] = min_core
    if "max_core" in fields:
        max_core = parse_scalar(fields["max_core"])
        if parse_semver(max_core) is None:
            raise Finding(f"{where}: max_core '{max_core}' is not a semver X.Y.Z")
        if parse_semver(max_core) < parse_semver(min_core):
            raise Finding(f"{where}: max_core {max_core} is below min_core {min_core}")
        note["max_core"] = max_core

    tools = parse_list(fields["requires_tools"], where) if "requires_tools" in fields else []
    for tool in tools:
        if not TOOL_RE.match(tool):
            raise Finding(f"{where}: requires_tools entry '{tool}' is not a tool name")
    if len(set(tools)) != len(tools):
        raise Finding(f"{where}: requires_tools has duplicates")
    note["requires_tools"] = tools
    note["source"] = parse_scalar(fields["source"])

    body = "\n".join(lines[end + 1 :]).strip("\n")
    if not body.strip():
        raise Finding(f"{where}: the note has no body")
    note["body"] = body
    return note


def note_paths(root: Path) -> list[Path]:
    d = root / NOTES_DIR
    if not d.is_dir():
        return []
    return sorted(p for p in d.iterdir() if p.is_file() and p.suffix == ".md" and p.name != README_NAME)


def render_bundle(notes: list[dict]) -> bytes:
    bundle = {"format": BUNDLE_FORMAT, "notes": sorted(notes, key=lambda n: n["id"])}
    return (json.dumps(bundle, indent=2, ensure_ascii=False) + "\n").encode("utf-8")


def load_notes(root: Path) -> list[dict]:
    notes = [parse_note(p) for p in note_paths(root)]
    seen: dict[str, int] = {}
    for note in notes:
        key = note["id"].casefold()
        seen[key] = seen.get(key, 0) + 1
        if seen[key] > 1:
            raise Finding(f"{NOTES_DIR}: id '{note['id']}' is used by more than one note")
    return notes


# --------------------------------------------------------------------------
# environment: latest core tag and routine field list


def latest_core_tag(root: Path) -> str | None:
    try:
        out = subprocess.run(
            ["git", "tag", "--list", "v*"], cwd=root, check=True, capture_output=True, text=True
        ).stdout
    except (OSError, subprocess.CalledProcessError):
        return None
    best = None
    for tag in out.split():
        m = TAG_RE.match(tag)
        if m:
            ver = (int(m[1]), int(m[2]), int(m[3]))
            best = ver if best is None or ver > best else best
    return ".".join(map(str, best)) if best else None


def load_routine_fields(source: str) -> set[str]:
    """Field keys of the routine schema. Raises Finding when unavailable."""
    try:
        if re.match(r"^https?://", source):
            with urllib.request.urlopen(source, timeout=30) as resp:  # noqa: S310 - fixed public URL
                raw = resp.read(1024 * 1024)
        else:
            raw = Path(source).read_bytes()
        data = json.loads(raw)
    except (OSError, urllib.error.URLError, ValueError) as exc:
        raise Finding(f"routine-fields.json is unavailable from {source}: {exc}") from None
    items = data.get("fields") if isinstance(data, dict) else data
    if not isinstance(items, list) or not items or not all(isinstance(i, str) and i for i in items):
        raise Finding(f"routine-fields.json from {source} is not a non-empty list of field names")
    keys: set[str] = set()
    for item in items:
        keys.add(item)
        keys.add(item.split(".")[-1])
    return keys


def check_body(note: dict, routine_keys: set[str]) -> None:
    where = f"{NOTES_DIR}/{note['id']}.md"
    for n, line in enumerate(note["body"].split("\n"), start=1):
        if YAML_FENCE_RE.match(line):
            raise Finding(f"{where}: body line {n}: yaml code blocks are not allowed in a note")
        m = KEY_LINE_RE.match(line)
        if m and m[1] in routine_keys:
            raise Finding(f"{where}: body line {n}: routine schema field key '{m[1]}:' is not allowed")
        for span in INLINE_CODE_RE.findall(line):
            for key in INLINE_KEY_RE.findall(span):
                if key in routine_keys:
                    raise Finding(
                        f"{where}: body line {n}: routine schema field key '{key}:' is not allowed"
                    )


# --------------------------------------------------------------------------
# commands


def cmd_build(root: Path) -> int:
    try:
        notes = load_notes(root)
    except Finding as exc:
        print(f"node-notes: {exc}", file=sys.stderr)
        return 1
    out = root / NOTES_DIR / BUNDLE_NAME
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(render_bundle(notes))
    print(f"node-notes: wrote {NOTES_DIR}/{BUNDLE_NAME} ({len(notes)} notes)")
    return 0


def check_layout(root: Path) -> None:
    d = root / NOTES_DIR
    if not d.is_dir():
        raise Finding(f"{NOTES_DIR}/ is missing")
    for p in sorted(d.iterdir()):
        name = p.name
        if p.is_dir() or p.is_symlink():
            raise Finding(f"{NOTES_DIR}/{name}: only plain files live in {NOTES_DIR}/")
        if name in (README_NAME, AUTHORS_NAME, BUNDLE_NAME) or name.endswith(".md"):
            continue
        raise Finding(f"{NOTES_DIR}/{name}: unexpected file (notes are <id>.md)")
    for name in (README_NAME, AUTHORS_NAME):
        if not (d / name).is_file():
            raise Finding(f"{NOTES_DIR}/{name} is missing")
    for name in (README_NAME, AUTHORS_NAME):
        for n, line in enumerate((d / name).read_text(encoding="utf-8").split("\n"), start=1):
            if CYRILLIC_RE.search(line):
                raise Finding(f"{NOTES_DIR}/{name}:{n}: Cyrillic text; this repository is English only")
    parse_authors((d / AUTHORS_NAME).read_text(encoding="utf-8"), f"{NOTES_DIR}/{AUTHORS_NAME}")


def cmd_check(root: Path, latest_core: str | None, routine_fields: str) -> int:
    try:
        check_layout(root)
        for p in note_paths(root):
            text = p.read_bytes().decode("utf-8", errors="replace")
            for n, line in enumerate(text.split("\n"), start=1):
                if CYRILLIC_RE.search(line):
                    raise Finding(f"{NOTES_DIR}/{p.name}:{n}: Cyrillic text; notes are English only")
        notes = load_notes(root)
        if notes:
            latest = latest_core or latest_core_tag(root)
            if not latest or parse_semver(latest) is None:
                raise Finding("no v* core tag found: min_core cannot be checked (fetch tags)")
            for note in notes:
                if parse_semver(note["min_core"]) > parse_semver(latest):
                    raise Finding(
                        f"{NOTES_DIR}/{note['id']}.md: min_core {note['min_core']} is above the "
                        f"latest core release {latest}"
                    )
            routine_keys = load_routine_fields(routine_fields)
            for note in notes:
                check_body(note, routine_keys)
        bundle = render_bundle(notes)
        if len(bundle) > BUNDLE_MAX_BYTES:
            raise Finding(f"the bundle is {len(bundle)} bytes, the limit is {BUNDLE_MAX_BYTES}")
        committed = root / NOTES_DIR / BUNDLE_NAME
        if not committed.is_file():
            raise Finding(f"{NOTES_DIR}/{BUNDLE_NAME} is missing: run python3 .github/node-notes.py build")
        if committed.read_bytes() != bundle:
            raise Finding(
                f"{NOTES_DIR}/{BUNDLE_NAME} is stale: run python3 .github/node-notes.py build and commit it"
            )
    except Finding as exc:
        print(f"node-notes: FAIL: {exc}", file=sys.stderr)
        return 1
    print(f"node-notes: ok ({len(notes)} notes, bundle {len(bundle)} bytes)")
    return 0


def parse_authors(text: str, where: str) -> set[str]:
    logins: set[str] = set()
    for n, line in enumerate(text.split("\n"), start=1):
        entry = line.split("#", 1)[0].strip()
        if not entry:
            continue
        if not LOGIN_RE.match(entry):
            raise Finding(f"{where}:{n}: '{entry}' is not a GitHub login")
        logins.add(entry.casefold())
    return logins


def git(root: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["git", *args], cwd=root, capture_output=True, text=True)


def cmd_authors(root: Path, base: str, head: str, author: str) -> int:
    diff = git(root, "diff", "--name-only", "--no-renames", "-z", f"{base}...{head}")
    if diff.returncode != 0:
        print(f"node-notes: cannot diff {base}...{head}: {diff.stderr.strip()}", file=sys.stderr)
        return 2
    changed = [p for p in diff.stdout.split("\0") if p]
    gated = [p for p in changed if p.startswith(f"{NOTES_DIR}/") or p in GATED_FILES]
    if not gated:
        print("node-notes: authors: the change does not touch node-notes, nothing to gate")
        return 0
    base_authors = git(root, "show", f"{base}:{NOTES_DIR}/{AUTHORS_NAME}")
    if base_authors.returncode != 0:
        base_tree = git(root, "ls-tree", "--name-only", base, f"{NOTES_DIR}/")
        head_tree = git(root, "ls-tree", "--name-only", head, f"{NOTES_DIR}/")
        head_notes = [
            p for p in head_tree.stdout.split()
            if p.endswith(".md") and p != f"{NOTES_DIR}/{README_NAME}"
        ]
        if base_tree.returncode == 0 and not base_tree.stdout.strip() and not head_notes:
            print(
                "node-notes: authors: bootstrap -- the base has no node-notes/ yet and the "
                "change adds no notes; every later change is gated by the AUTHORS it adds"
            )
            return 0
        print(
            f"node-notes: authors: FAIL: {NOTES_DIR}/{AUTHORS_NAME} is missing in the base {base}",
            file=sys.stderr,
        )
        return 1
    try:
        allowed = parse_authors(base_authors.stdout, f"{base}:{NOTES_DIR}/{AUTHORS_NAME}")
    except Finding as exc:
        print(f"node-notes: authors: FAIL: {exc}", file=sys.stderr)
        return 1
    if author.casefold() not in allowed:
        print(
            f"node-notes: authors: FAIL: '{author}' changes {', '.join(gated)} but is not listed "
            f"in {NOTES_DIR}/{AUTHORS_NAME} of the base {base}",
            file=sys.stderr,
        )
        return 1
    print(f"node-notes: authors: '{author}' is listed in the base AUTHORS")
    return 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Build and check node-notes/.")
    ap.add_argument("--root", default=".", help="repository root (default: current directory)")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("build")
    c = sub.add_parser("check")
    c.add_argument("--latest-core", help="latest core release X.Y.Z (default: highest v* git tag)")
    c.add_argument(
        "--routine-fields",
        default=os.environ.get("NODE_NOTES_ROUTINE_FIELDS", DEFAULT_ROUTINE_FIELDS_URL),
        help="path or URL of routine-fields.json (default: asset of the latest core release)",
    )
    a = sub.add_parser("authors")
    a.add_argument("--base", required=True)
    a.add_argument("--head", required=True)
    a.add_argument("--author", required=True)
    args = ap.parse_args(argv)
    root = Path(args.root).resolve()
    if args.cmd == "build":
        return cmd_build(root)
    if args.cmd == "check":
        return cmd_check(root, args.latest_core, args.routine_fields)
    if not LOGIN_RE.match(args.author):
        print(f"node-notes: authors: '{args.author}' is not a GitHub login", file=sys.stderr)
        return 2
    return cmd_authors(root, args.base, args.head, args.author)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
